all : Sol1a Sol1b \
      Sol2a Sol2b Sol2c Sol2d \
      div_zero

clean_all:
	rm Sol1a Sol1b \
       Sol2a Sol2b Sol2c Sol2d\
       div_zero

Sol1a: Sol1a.c
Sol1b: Sol1b.c

Sol2a: Sol2a.c
Sol2b: Sol2b.c
Sol2c: Sol2c.c
Sol2d: Sol2d.c

div_zero: div_zero.c